name: CI
on: [push]

jobs:
  build:
    timeout-minutes: 60

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: ./gradlew android:testRelease
